# Generated by Django 5.0.2 on 2024-02-12 17:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=100)),
                ('build_notes', models.TextField()),
                ('url_build_pic', models.TextField()),
                ('owner_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Build_Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FBBN.build')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part_Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('url_product', models.TextField()),
                ('url_picture', models.TextField()),
                ('other_notes', models.TextField()),
                ('added_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='build_accessories',
            field=models.ManyToManyField(to='FBBN.part_accessory'),
        ),
        migrations.CreateModel(
            name='Accessory_Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FBBN.part_accessory')),
            ],
        ),
        migrations.CreateModel(
            name='Part_Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('is_electric_assist', models.BooleanField()),
                ('category', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('url_product', models.TextField()),
                ('url_picture', models.TextField()),
                ('other_notes', models.TextField()),
                ('added_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='build_bike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FBBN.part_bike'),
        ),
        migrations.CreateModel(
            name='Bike_Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FBBN.part_bike')),
            ],
        ),
        migrations.CreateModel(
            name='Part_Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('location_on_bike', models.CharField(max_length=100)),
                ('max_weight_lb', models.CharField(max_length=100)),
                ('url_product', models.TextField()),
                ('url_picture', models.TextField()),
                ('other_notes', models.TextField()),
                ('added_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='build_racks',
            field=models.ManyToManyField(to='FBBN.part_rack'),
        ),
        migrations.CreateModel(
            name='Part_Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('mounting_type', models.CharField(max_length=100)),
                ('location_on_bike', models.CharField(max_length=100)),
                ('url_product', models.TextField()),
                ('url_picture', models.TextField()),
                ('other_notes', models.TextField()),
                ('added_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='build_seats',
            field=models.ManyToManyField(to='FBBN.part_seat'),
        ),
        migrations.CreateModel(
            name='Part_Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('mounting_type', models.CharField(max_length=100)),
                ('volume_liters', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('url_product', models.TextField()),
                ('url_picture', models.TextField()),
                ('other_notes', models.TextField()),
                ('added_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='build_storages',
            field=models.ManyToManyField(to='FBBN.part_storage'),
        ),
        migrations.CreateModel(
            name='Part_Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('passenger_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('url_product', models.TextField()),
                ('url_picture', models.TextField()),
                ('other_notes', models.TextField()),
                ('added_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='build_trailers',
            field=models.ManyToManyField(to='FBBN.part_trailer'),
        ),
        migrations.CreateModel(
            name='Rack_Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FBBN.part_rack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seat_Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FBBN.part_seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Storage_Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FBBN.part_storage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer_Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FBBN.part_trailer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
