# Generated by Django 5.0.2 on 2024-02-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FBBN', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part_trailer',
            name='is_stroller',
            field=models.BooleanField(default=False),
        ),
    ]
