# Generated by Django 5.0.2 on 2024-02-12 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FBBN', '0003_alter_part_rack_max_weight_lb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='build_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='url_build_pic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part_bike',
            name='other_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part_bike',
            name='url_picture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part_bike',
            name='url_product',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part_rack',
            name='max_weight_lb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='part_rack',
            name='other_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part_rack',
            name='url_picture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part_rack',
            name='url_product',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part_seat',
            name='other_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part_seat',
            name='url_picture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part_seat',
            name='url_product',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part_storage',
            name='other_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part_storage',
            name='url_picture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part_storage',
            name='url_product',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part_storage',
            name='volume_liters',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='part_trailer',
            name='other_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part_trailer',
            name='url_picture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part_trailer',
            name='url_product',
            field=models.TextField(blank=True, null=True),
        ),
    ]
