# Generated by Django 5.0.2 on 2024-02-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FBBN', '0004_alter_build_build_notes_alter_build_url_build_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='build_accessories',
            field=models.ManyToManyField(blank=True, null=True, to='FBBN.part_accessory'),
        ),
        migrations.AlterField(
            model_name='build',
            name='build_racks',
            field=models.ManyToManyField(blank=True, null=True, to='FBBN.part_rack'),
        ),
        migrations.AlterField(
            model_name='build',
            name='build_seats',
            field=models.ManyToManyField(blank=True, null=True, to='FBBN.part_seat'),
        ),
        migrations.AlterField(
            model_name='build',
            name='build_storages',
            field=models.ManyToManyField(blank=True, null=True, to='FBBN.part_storage'),
        ),
        migrations.AlterField(
            model_name='build',
            name='build_trailers',
            field=models.ManyToManyField(blank=True, null=True, to='FBBN.part_trailer'),
        ),
    ]
